config/routes.rb
Rails.application.routes.draw do
  resources :finances do
    collection do
      get :finance
    end
  end

  get 'session/login'

  get 'session/logout'

  post 'session/authenticate'

  resources :quotes

  resources :staffs

  resources :cars

  resources :states

  resources :customers

   root 'session#login'

end

app/models/finance.rb
class Finance < ActiveRecord::Base
validates :loan, presence: true
validates :interest, presence: true
validates :term, presence: true


  def self.pmt
    @@pmt
  end

  #calculate values in table and return as finance array according to formula
  def self.amort_table(loan = 0.00, interest = 0.00, term = 0)
    Rails.logger.debug "Inputs: #{loan} #{interest} #{term}"
    finance = []
    fixed = loan
    (1..term*12).each do |i|
      rate = interest/12
      @@pmt = ((rate*fixed)/(1-(1+rate)**(-term*12)))
      finance << loan - (@@pmt - (loan*rate))

      last_amount = loan - (@@pmt - (loan*rate))

      loan = last_amount
    end
    return finance
  end

  def amort_table
    return self.class.amort_table(self.loan, self.interest, self.term)
  end
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]

  # GET /finances
  # GET /finances.json

  def finance
    loan =params[:loan]
    interest = params[:interest]
    term = params[:term]
    @finance_array = Finance.amort_table(loan.to_d, interest.to_d, term.to_i)

  end

  def index
    @finances = Finance.all
  end

  # GET /finances/1
  # GET /finances/1.json
  def show
    @finance_array = @finance.amort_table
  end

  # GET /finances/new
  def new
    @finance = Finance.new
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances
  # POST /finances.json
  def create
    @finance = Finance.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to @finance, notice: 'Finance was successfully created.' }
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1
  # PATCH/PUT /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to @finance, notice: 'Finance was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1
  # DELETE /finances/1.json
  def destroy
    @finance.destroy
    respond_to do |format|
      format.html { redirect_to finances_url, notice: 'Finance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finance_params
      params.require(:finance).permit(:loan, :interest, :term)
    end
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/views/finances/_finance.erb
<table class="CSSTableGenerator" width="30%">
  <th>Period</th>
  <th>Balance</th>
  <th>Payment</th>
  <% @finance_array.each_with_index do |p,n|  %>
      <tr>
        <td><%= n + 1 %></td>
        <td><%= p.round(2) %></td>
        <td><%= Finance.pmt.round(2)%></td>
      </tr>
  <% end %>

</table>

app/views/finances/_form.html.erb
<%= form_for(@finance) do |f| %>
  <% if @finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% @finance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :loan %><br>
    <%= f.text_field :loan %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :term %><br>
    <%= f.select :term, (3..5) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<div id = "finance_table" class = "table-format"></div>

app/views/finances/edit.html.erb
<h1>Editing Finance</h1>

<%= render 'form' %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

app/views/finances/finance.js.erb
$('#finance_table').html("<%= j (render 'finance') %>")

//Jquery selector for where to put stuff when you're done i.e growth-table
//.html means take what give you and treat it as html
//render population_table renders the table
//you have to tell the .erb that this is javascript so that's what the 'j' is for
//at this 'j' it "escapes" the javascript

app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Finances</h1>

<table>
  <thead>
    <tr>
      <th class = "list_title">Loan</th>
      <th class = "list_title">Interest</th>
      <th class = "list_title">Term</th>
      <th class = "list_title">Actions</th>
    </tr>
  </thead>


    <% @finances.each do |finance| %>
      <tr class = "<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class = "list_loan"><%= number_to_currency(finance.loan, :unit => "$", :delimeter => ".") %></td>
        <td class = "list_interest"><%= number_with_precision(finance.interest, precision: 2) %></td>
        <td class = "list_term"><%= finance.term %></td>
        <td class = "list_actions">
          <%= link_to 'Show', finance %>
        <%= link_to 'Edit', edit_finance_path(finance) %>
        <%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
</table>

<br>

<%= link_to 'New Finance', new_finance_path %>

app/views/finances/new.html.erb
<h1>New Finance</h1>

<%= render 'form' %>

<%= link_to 'Back', finances_path %>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Loan:</strong>
  <%= @finance.loan %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @finance.interest %>
</p>

<p>
  <strong>Term:</strong>
  <%= @finance.term %>
</p>

<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>