config/routes.rb
Rails.application.routes.draw do
  resources :finances do
    collection do
      get :finance
    end
  end

  get 'session/login'

  get 'session/logout'

  post 'session/authenticate'

  resources :quotes

  resources :staffs

  resources :cars

  resources :states

  resources :customers

   root 'session#login'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :car
  belongs_to :staff
  belongs_to :customer
  validates_associated :car
  validates_associated :staff
  validates_associated :customer
  validates :wholesale, presence: true

  validates :interest, presence: true
  validates :principle, presence: true

  validates :status, presence: true
  validates :staff_id, presence: true
  validates :customer_id, presence: true
  validates :car_id, presence: true

  def status_value
    if self.status == "0"
      return "Pending"
    else
      return "Sold"
    end
  end

  def markup_calc
    mark = wholesale + (wholesale * 0.10)
    return mark
  end

  def total_calc
    cal = markup_calc + (markup_calc * interest) - principle
    tot = cal + (cal * 0.043)
    return tot
  end

  def markamt
    amt = wholesale * 0.10
    return amt
  end

  def taxsale
    tax = markup_calc * 0.043
    return tax
  end

  def self.profit
    profit = 0
    Quote.all.each do |i|
      if i.status == "1"
        profit += i.total_calc
      end
    end

    return profit
  end

  def self.markupsale
    revenue = 0
    Quote.all.each do |i|
      if i.status == "1"
        revenue += i.markamt
      end
    end
    return revenue
  end

  def self.taxrev
    taxrevenue = 0
    Quote.all.each do |i|
      if i.status == "1"
        taxrevenue += i.taxsale
      end
    end
    return taxrevenue
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:wholesale, :markup, :interest, :principle, :total, :status, :staff_id, :customer_id, :car_id)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wholesale %><br>
    <%= f.text_field :wholesale %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :principle %><br>
    <%= f.text_field :principle %>
  </div>
  <div class="field">
    <%= f.label :status, "Sold" %><br>
    <%= f.check_box :status, :as => :check_boxes, collection: [['Pending', 'Sold']] %>
  </div>
  <div class="field">
    <%= f.label :staff_id, "Salesperson" %><br>
    <%= f.collection_select(:staff_id, Staff.all, :id, :staff_name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select(:customer_id, Customer.all, :id, :customer_name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :car_id %><br>
    <%= f.collection_select(:car_id, Car.all, :id, :VIN, prompt: true) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quotes</h1>

<table>
  <thead>
    <tr>
      <th class = "list_title">Wholesale</th>
      <th class = "list_title">Markup</th>
      <th class = "list_title">Interest</th>
      <th class = "list_title">Principle</th>
      <th class = "list_title">Total</th>
      <th class = "list_title">Status</th>
      <th class = "list_title">Staff</th>
      <th class = "list_title">Customer</th>
      <th class = "list_title">Car</th>
      <th class = "list_title">Actions</th>
    </tr>
  </thead>

    <% @quotes.each do |quote| %>
      <tr class = "<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class = "list_wholesale"><%= number_to_currency(quote.wholesale, :unit => "$", :delimeter => ".") %></td>
        <td class = "list_markup"><%= number_to_currency(quote.markup_calc, :unit => "$", :delimeter => ".") %></td>
        <td class = "list_interest"><%= number_with_precision(quote.interest, precision: 2) %></td>
        <td class = "list_principle"><%= number_to_currency(quote.principle, :unit => "$", :delimeter => ".") %></td>
        <td class = "list_total"><%= number_to_currency(quote.total_calc, :unit => "$", :delimeter=> ".") %></td>
        <td class = "list_status"><%= quote.status_value %></td>
        <td class = "list_staff"><%= quote.staff.staff_name %></td>
        <td class = "list_customer"><%= quote.customer.customer_name %></td>
        <td class = "list_car"><%= quote.car.VIN %></td>

        <td class = "list_actions">
        <%= link_to 'Show', quote %>
        <%= link_to 'Edit', edit_quote_path(quote) %>
        <%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>


  </table>
<br>
<br>

<th><b>Total Gross Revenue = </b></th> <td><%= number_to_currency(Quote.profit, :unit => "$", :delimeter => ".") %></td><br>
   <th><b> Net Profit = </b></th> <td><%= number_to_currency(Quote.markupsale, :unit => "$", :delimeter => ".") %></td><br>
<th><b>Sales Tax Totals = </b></th> <td><%= number_to_currency(Quote.taxrev, :unit => "$", :delimeter => ".") %></td>



<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wholesale:</strong>
  <%= number_to_currency(@quote.wholesale, :unit => "$", :delimeter => ".") %>
</p>

<p>
  <strong>Markup:</strong>
  <%= number_to_currency(@quote.markup_calc, :unit => "$", :delimeter => ".") %>
</p>

<p>
  <strong>Interest:</strong>
  <%= number_with_precision(@quote.interest, precision: 2) %>
</p>

<p>
  <strong>Principle:</strong>
  <%= number_to_currency(@quote.principle, :unit => "$", :delimeter => ".") %>
</p>

<p>
  <strong>Total:</strong>
  <%= number_to_currency(@quote.total_calc, :unit => "$", :delimeter => ".") %>
</p>

<p>
  <strong>Status:</strong>
  <%= @quote.status_value %>
</p>

<p>
  <strong>Salesperson:</strong>
  <%= @quote.staff.staff_name %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.customer_name %>
</p>

<p>
  <strong>Car:</strong>
  <%= @quote.car.VIN %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>